env: flex
runtime: python
runtime_config:
  python_version: 2

service: serviceb

entrypoint: gunicorn -b :$PORT 'serviceb:create_app()'

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.6
